name: contacts
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  flutter_google_places_autocomplete: ^0.0.5
  flutter_launcher_icons: ^0.3.3
  shared_preferences: ^0.4.2
  json_annotation: ^0.2.4
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  url_launcher: ^3.0.2
  image_picker: ^0.4.5
  sqflite: ^0.11.0
  http: ^0.11.3+16
  intl: ^0.15.6

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.2

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
